engines:
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: ".eslintrc.yaml"

checks:
  similar-code:
    enabled: false
  method-complexity:
    config:
      threshold: 10

ratings:
   paths:
   - "**.js"
